# Generated by Django 4.0.5 on 2022-06-18 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=127)),
                ('iban', models.CharField(max_length=27, unique=True)),
                ('foto', models.CharField(max_length=20)),
                ('euro', models.FloatField()),
                ('dollari', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita_spesa', models.FloatField()),
                ('quantita_comprata', models.FloatField()),
                ('valuta_comprata', models.CharField(max_length=3)),
                ('data', models.DateField()),
                ('fk_utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.utente')),
            ],
        ),
    ]
