# Generated by Django 4.0.5 on 2022-06-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
