# Generated by Django 4.0.5 on 2022-06-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_utente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='foto',
            field=models.CharField(default='default.png', max_length=20),
        ),
    ]
